#!/bin/sh

set -e

bundle exec jekyll build
# bundle exec htmlproofer ./_site --check-html --check-sri #this thing errors out. Need to read the documentation to continue without erroring out
bundle exec rubocop -D
bundle exec script/validate-html
gem build jekyll-theme.gemspec
