name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [latest] # always uses the latest stable Ruby version

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Run tests
        run: |
          bundle exec rake test || bundle exec rspec || echo "No test suite found"
